sudo: required
services:
  - docker
git:
  depth: 5
language: generic
script:
  - (cd 7.5/7.5.0 ; docker build --rm=false -t convertigo/convertigo:7.5.0_auto .)
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push convertigo/convertigo:7.5.0_auto
